from __future__ import annotations
from typing import Iterator

def version() -> str: ...

class Vec2:
    def __init__(self, x: float = ..., y: float = ...) -> None: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, v: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    def norm(self) -> float: ...
    def unit(self) -> Vec2: ...
    def dot(self, other: Vec2) -> float: ...
    def distance(self, other: Vec2) -> float: ...
    def __add__(self, other: Vec2) -> Vec2: ...
    def __sub__(self, other: Vec2) -> Vec2: ...
    def __mul__(self, s: float) -> Vec2: ...
    def __rmul__(self, s: float) -> Vec2: ...
    def __truediv__(self, s: float) -> Vec2: ...
    def __neg__(self) -> Vec2: ...
    def __eq__(self, other: object) -> bool: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Vec3:
    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, v: float) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def norm(self) -> float: ...
    def unit(self) -> Vec3: ...
    def dot(self, other: Vec3) -> float: ...
    def distance(self, other: Vec3) -> float: ...
    def __add__(self, other: Vec3) -> Vec3: ...
    def __sub__(self, other: Vec3) -> Vec3: ...
    def __mul__(self, s: float) -> Vec3: ...
    def __rmul__(self, s: float) -> Vec3: ...
    def __truediv__(self, s: float) -> Vec3: ...
    def __neg__(self) -> Vec3: ...
    def __eq__(self, other: object) -> bool: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Simulation:
    def __init__(self, state_size: int = ..., max_devices: int = ..., dimension: int = ...) -> None: ...
    def set_callback(self, fn: callable) -> None: ...
    def run(self, end_time: float) -> None: ...
    def step(self) -> float: ...
    def next_time(self) -> float: ...
    def device_count(self) -> int: ...
    def get_ids(self) -> list[int]: ...
    def get_state(self, device_id: int) -> list[float] | None: ...
    def get_all_states(self) -> tuple[list[int], list[list[float]]]: ...
    def destroy(self) -> None: ...
    def __enter__(self) -> Simulation: ...
    def __exit__(self, *_) -> None: ...
    @staticmethod
    def compile_info() -> dict: ...

